# Generated by Django 4.2.6 on 2023-10-27 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0007_alter_item_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image_url',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
