# Generated by Django 4.2.6 on 2023-10-25 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contactParms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_contact_whatsapp_phone', models.CharField()),
            ],
        ),
    ]
