# Generated by Django 4.2.6 on 2023-10-25 02:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='contactParms',
            new_name='contactParm',
        ),
        migrations.AlterModelOptions(
            name='contactparm',
            options={'verbose_name_plural': 'contactParms'},
        ),
    ]
