# Generated by Django 4.2.6 on 2023-10-25 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_contactparms_contactparm_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactparm',
            name='product_contact_whatsapp_text',
            field=models.TextField(default='Oi, gostaria de saber mais sobre &produto.'),
            preserve_default=False,
        ),
    ]
