# Generated by Django 4.2.6 on 2023-10-26 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_contactparm_product_contact_whatsapp_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactparm',
            name='product_contact_whatsapp_phone',
            field=models.CharField(max_length=16),
        ),
    ]
